#    image: cbck/couchmart:python2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchmart
spec:
  selector:
    matchLabels:
      app: couchmart
  template:
    metadata:
      labels:
        app: couchmart
    spec:
      containers:
      - name: couchmart
        image: cbck/couchmart:latest
        imagePullPolicy: Always
