---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission-cktest2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission-cktest2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-operator-admission
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admission-cktest2
  namespace: cktest2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission-cktest2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-operator-admission-cktest2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchbase-operator-admission-cktest2
    spec:
      containers:
      - args:
        - --logtostderr
        - --stderrthreshold
        - "0"
        - --tls-cert-file
        - /var/run/secrets/couchbase.com/couchbase-operator-admission/tls-cert-file
        - --tls-private-key-file
        - /var/run/secrets/couchbase.com/couchbase-operator-admission/tls-private-key-file
        command:
        - couchbase-operator-admission
        image: couchbase/admission-controller:1.2.1
        name: couchbase-operator-admission-cktest2
        ports:
        - containerPort: 8443
          name: https
        resources: {}
        volumeMounts:
        - mountPath: /var/run/secrets/couchbase.com/couchbase-operator-admission
          name: couchbase-operator-admission-cktest2
          readOnly: true
      serviceAccountName: couchbase-operator-admission-cktest2
      volumes:
      - name: couchbase-operator-admission-cktest2
        secret:
          secretName: couchbase-operator-admission
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission-cktest2
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: couchbase-operator-admission-cktest2
status:
  loadBalancer: {}

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission-cktest2
webhooks:
- clientConfig:
    caBundle: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICA2NDowODpiZTo5ZjoyZTozNzozZjpjMjo4YzpjODowNDoyNTo3MTo2ODpiNzoyNAogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IENOPUNvdWNoYmFzZSBDQQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IFNlcCAxOSAxMzo1OTo1OSAyMDE5IEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBTZXAgIDMgMTM6NTk6NTkgMjAyMiBHTVQKICAgICAgICBTdWJqZWN0OiBDTj1jb3VjaGJhc2Utc2VydmVyCiAgICAgICAgU3ViamVjdCBQdWJsaWMgS2V5IEluZm86CiAgICAgICAgICAgIFB1YmxpYyBLZXkgQWxnb3JpdGhtOiByc2FFbmNyeXB0aW9uCiAgICAgICAgICAgICAgICBQdWJsaWMtS2V5OiAoMjA0OCBiaXQpCiAgICAgICAgICAgICAgICBNb2R1bHVzOgogICAgICAgICAgICAgICAgICAgIDAwOmJkOjU4OmNjOmIyOjRkOjEzOjA5OmM5OmFmOjQ3OjUzOjViOmNiOjhlOgogICAgICAgICAgICAgICAgICAgIDJiOjRmOjY3OjM5OmI1OmFlOmUxOjRiOmVjOmE5OmRiOmY1OjE4OmQ5OjY1OgogICAgICAgICAgICAgICAgICAgIGU1OmI2OjE0OjAyOjcwOmNmOmNmOmM3OmVmOjUxOjJkOmM0OjY4OjhlOjU4OgogICAgICAgICAgICAgICAgICAgIGJjOmQzOjQ3Ojg0OjE0OmQ3OmUwOmVjOjNlOmFjOjY5OjdmOjczOmEwOjY4OgogICAgICAgICAgICAgICAgICAgIDJhOjVhOjhiOjE5OjIxOjM2OmZlOjYyOmY1OmQyOjM2Ojg0OjUyOjVkOmE5OgogICAgICAgICAgICAgICAgICAgIGJmOmMwOjk5OmQyOjI5OmUyOjU5OjdmOmNhOjczOjk5OjA3OjZjOjIzOmY1OgogICAgICAgICAgICAgICAgICAgIGI1OjU1OjA3OmEwOjNlOmEwOmE5OjI3OjFkOmM3OjMyOjM5Ojk2OjQzOmUyOgogICAgICAgICAgICAgICAgICAgIDkyOjVmOmRjOjZkOjJkOmJlOjE5OjVkOjdjOmQ1OjYzOmIxOmQ1OjAyOjYzOgogICAgICAgICAgICAgICAgICAgIGFhOjMxOmRiOjcxOjZjOjU5OmZhOjE2OjM4OjUzOjUxOjRmOjFlOjcxOmNhOgogICAgICAgICAgICAgICAgICAgIDA3OjM2OjNkOmFlOmM0OmY5OmI4OjBkOjI4OmRiOjMwOmE2OjZiOmFjOjBiOgogICAgICAgICAgICAgICAgICAgIDY0OjE2OjFlOjRkOjBjOmMzOjQ5OmMwOmJkOmY2OmUwOmExOmQ1OjAwOjg4OgogICAgICAgICAgICAgICAgICAgIGY0OjA0Ojc4OmY3OmUwOjE4OjA3OmQ5OjNlOmFhOjE5OmM2OmVmOjI5Ojg4OgogICAgICAgICAgICAgICAgICAgIGJiOmRhOmQwOjU5OmJjOjc3OmI3OjU3OjkyOjFjOmNjOjVjOjdiOjhiOmJiOgogICAgICAgICAgICAgICAgICAgIGJmOjI2OmEwOjY3OmU2OjM3OjU3OmY4OjFlOjMxOjJhOjkyOmU0OjIyOjcwOgogICAgICAgICAgICAgICAgICAgIDBkOjJjOmE0OmVjOjBhOjBhOmRiOjJmOjY2OmU4OmYwOjNlOjcwOjBjOmJmOgogICAgICAgICAgICAgICAgICAgIDI3OmExOmIxOmM1OjUzOjdmOmNmOmQwOmZjOjQ2OjM4OmI5OmQ3OmNkOmE3OgogICAgICAgICAgICAgICAgICAgIDRkOmM3OmJmOjkwOjlkOjFhOjk1OjBlOjdmOmJjOjc0OjdlOmEyOjhiOmUzOgogICAgICAgICAgICAgICAgICAgIGNlOmExCiAgICAgICAgICAgICAgICBFeHBvbmVudDogNjU1MzcgKDB4MTAwMDEpCiAgICAgICAgWDUwOXYzIGV4dGVuc2lvbnM6CiAgICAgICAgICAgIFg1MDl2MyBCYXNpYyBDb25zdHJhaW50czogCiAgICAgICAgICAgICAgICBDQTpGQUxTRQogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBENTo5MzpEOTowMzo3Rjo1RDoyRTpBQjpBRTo0MTpERTpGQjpGMjo0RTpBODoyQjpFMTo5QTo5OTpBRQogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIGtleWlkOjVDOjUzOjdFOjE2OjkyOjU4OkZCOjY5OkIzOkYzOkRCOjg2OkM4OjY0OjE1OkUyOjc1OkU1OkMzOkU4CiAgICAgICAgICAgICAgICBEaXJOYW1lOi9DTj1Db3VjaGJhc2UgQ0EKICAgICAgICAgICAgICAgIHNlcmlhbDpGRjpERDpDRjpENTo3RDpGRTo1RDowRgoKICAgICAgICAgICAgWDUwOXYzIEV4dGVuZGVkIEtleSBVc2FnZTogCiAgICAgICAgICAgICAgICBUTFMgV2ViIFNlcnZlciBBdXRoZW50aWNhdGlvbgogICAgICAgICAgICBYNTA5djMgS2V5IFVzYWdlOiAKICAgICAgICAgICAgICAgIERpZ2l0YWwgU2lnbmF0dXJlLCBLZXkgRW5jaXBoZXJtZW50CiAgICAgICAgICAgIFg1MDl2MyBTdWJqZWN0IEFsdGVybmF0aXZlIE5hbWU6IAogICAgICAgICAgICAgICAgRE5TOiouY2ItZXhhbXBsZS5ja3Rlc3QyLnN2YywgRE5TOiouY2t0ZXN0Mi5zdmMKICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgIDQ0OmZlOjU4OjEzOmYwOjQzOjNkOjcxOjA1OjkzOjBjOjg0OjQ5OmY2Ojk1Ojk1OmRlOjVlOgogICAgICAgICA2NTo3YzphNjpmMjo1NDo2Mjo3YTo3ODpjYTphMTo0MTpiMjo3MTozZToxOTpjZTphNjpkNDoKICAgICAgICAgODc6MTQ6OTI6NDc6Y2Q6ODE6M2I6ODQ6ODQ6NzI6OWU6YmM6NDI6NTE6NDM6Yjk6Y2Q6NDc6CiAgICAgICAgIGEyOjk5OjljOjM2Ojg1OjRkOmI1OmIzOjljOjIwOmM5OmYxOjViOmJjOjcwOmI1OjRhOmMwOgogICAgICAgICBmZjo4NDpjMDowZjo0NTowNjo4NDo0Mzo0YzoyMjozYjpiYzplMzpkYToyYTo3ZDplOTo3NToKICAgICAgICAgM2Q6YWI6OTY6Mjc6NzE6M2E6M2Y6MmY6N2U6M2Y6YWY6MGM6Yzc6YWY6ODM6MDU6ODk6OWU6CiAgICAgICAgIGZiOmU1OjI4OjIyOjgxOjlhOjk2OjIyOjlkOmQxOjc1Ojc5OmQxOjhhOmVmOjlhOmMyOjZhOgogICAgICAgICA5MjphMjpjMzpjNjphYjo2YTpkMToyMTpmNzowNDphMDo4YTo5ZjoxMTphMTo4NzpjNTphNDoKICAgICAgICAgNGI6YjE6OGQ6Nzk6NTI6ZTk6ZTI6MDI6ZTM6NWU6YmE6NDQ6YmQ6MmE6NDk6MGI6NGQ6MmM6CiAgICAgICAgIDI0OjFmOmQ5OjY1OmI1OjA3OjUxOjBhOjk2OjQ1OjBiOjJiOjY1OjliOjM0OjA4OmYyOjgwOgogICAgICAgICA1ODoxMToxYjo2MTpiZToxMTphNTpkZTpkNjoxMDoyYjpkZjowNToyMjo2MDo4YjozNDpkOToKICAgICAgICAgNGE6OTY6OGQ6MjE6YmY6ZTA6YWY6Mjk6ZTc6NjU6YjM6NDk6YzQ6ZGE6Nzg6YmQ6MzA6Mjg6CiAgICAgICAgIDE4OjQ1Ojk5OjMwOjA5OjAzOjkxOjg3OjBmOmE4OmZiOmU4OjY4Ojk2OjZhOmU4OjRjOjViOgogICAgICAgICA0ZTo2MDo5NjpkMjo3ZjpkMToyNTowNjo0MjpjMDo5Mjo5MjozZTpkMDplMTozYTpkMTo3YjoKICAgICAgICAgNjc6ZDk6ZDE6MDkKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpVENDQW5HZ0F3SUJBZ0lRWkFpK255NDNQOEtNeUFRbGNXaTNKREFOQmdrcWhraUc5dzBCQVFzRkFEQVgKTVJVd0V3WURWUVFEREF4RGIzVmphR0poYzJVZ1EwRXdIaGNOTVRrd09URTVNVE0xT1RVNVdoY05Nakl3T1RBegpNVE0xT1RVNVdqQWJNUmt3RndZRFZRUUREQkJqYjNWamFHSmhjMlV0YzJWeWRtVnlNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2VmpNc2swVENjbXZSMU5ieTQ0clQyYzV0YTdoUyt5cDIvVVkKMldYbHRoUUNjTS9QeCs5UkxjUm9qbGk4MDBlRUZOZmc3RDZzYVg5em9HZ3FXb3NaSVRiK1l2WFNOb1JTWGFtLwp3Sm5TS2VKWmY4cHptUWRzSS9XMVZRZWdQcUNwSngzSE1qbVdRK0tTWDl4dExiNFpYWHpWWTdIVkFtT3FNZHR4CmJGbjZGamhUVVU4ZWNjb0hOajJ1eFBtNERTamJNS1pyckF0a0ZoNU5ETU5Kd0wzMjRLSFZBSWowQkhqMzRCZ0gKMlQ2cUdjYnZLWWk3MnRCWnZIZTNWNUljekZ4N2k3dS9KcUJuNWpkWCtCNHhLcExrSW5BTkxLVHNDZ3JiTDJibwo4RDV3REw4bm9iSEZVMy9QMFB4R09Mblh6YWROeDcrUW5ScVZEbis4ZEg2aWkrUE9vUUlEQVFBQm80SE1NSUhKCk1Ba0dBMVVkRXdRQ01BQXdIUVlEVlIwT0JCWUVGTldUMlFOL1hTNnJya0hlKy9KT3FDdmhtcG11TUVjR0ExVWQKSXdSQU1ENkFGRnhUZmhhU1dQdHBzL1BiaHNoa0ZlSjE1Y1Bvb1J1a0dUQVhNUlV3RXdZRFZRUUREQXhEYjNWagphR0poYzJVZ1EwR0NDUUQvM2MvVmZmNWREekFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTEJnTlZIUThFCkJBTUNCYUF3TWdZRFZSMFJCQ3N3S1lJWUtpNWpZaTFsZUdGdGNHeGxMbU5yZEdWemRESXVjM1pqZ2cwcUxtTnIKZEdWemRESXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCRS9sZ1Q4RU05Y1FXVERJUko5cFdWM2w1bApmS2J5VkdKNmVNcWhRYkp4UGhuT3B0U0hGSkpIellFN2hJUnlucnhDVVVPNXpVZWltWncyaFUyMXM1d2d5ZkZiCnZIQzFTc0QvaE1BUFJRYUVRMHdpTzd6ajJpcDk2WFU5cTVZbmNUby9MMzQvcnd6SHI0TUZpWjc3NVNnaWdacVcKSXAzUmRYblJpdSthd21xU29zUEdxMnJSSWZjRW9JcWZFYUdIeGFSTHNZMTVVdW5pQXVOZXVrUzlLa2tMVFN3awpIOWxsdFFkUkNwWkZDeXRsbXpRSThvQllFUnRodmhHbDN0WVFLOThGSW1DTE5ObEtsbzBoditDdktlZGxzMG5FCjJuaTlNQ2dZUlprd0NRT1JodytvKytob2xtcm9URnRPWUpiU2Y5RWxCa0xBa3BJKzBPRTYwWHRuMmRFSgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: couchbase-operator-admission-cktest2
      namespace: cktest2
      path: /couchbaseclusters/mutate
  name: couchbase-operator-admission-cktest2.cktest2.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: couchbase-operator-admission-cktest2
webhooks:
- clientConfig:
    caBundle: Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICA2NDowODpiZTo5ZjoyZTozNzozZjpjMjo4YzpjODowNDoyNTo3MTo2ODpiNzoyNAogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IENOPUNvdWNoYmFzZSBDQQogICAgICAgIFZhbGlkaXR5CiAgICAgICAgICAgIE5vdCBCZWZvcmU6IFNlcCAxOSAxMzo1OTo1OSAyMDE5IEdNVAogICAgICAgICAgICBOb3QgQWZ0ZXIgOiBTZXAgIDMgMTM6NTk6NTkgMjAyMiBHTVQKICAgICAgICBTdWJqZWN0OiBDTj1jb3VjaGJhc2Utc2VydmVyCiAgICAgICAgU3ViamVjdCBQdWJsaWMgS2V5IEluZm86CiAgICAgICAgICAgIFB1YmxpYyBLZXkgQWxnb3JpdGhtOiByc2FFbmNyeXB0aW9uCiAgICAgICAgICAgICAgICBQdWJsaWMtS2V5OiAoMjA0OCBiaXQpCiAgICAgICAgICAgICAgICBNb2R1bHVzOgogICAgICAgICAgICAgICAgICAgIDAwOmJkOjU4OmNjOmIyOjRkOjEzOjA5OmM5OmFmOjQ3OjUzOjViOmNiOjhlOgogICAgICAgICAgICAgICAgICAgIDJiOjRmOjY3OjM5OmI1OmFlOmUxOjRiOmVjOmE5OmRiOmY1OjE4OmQ5OjY1OgogICAgICAgICAgICAgICAgICAgIGU1OmI2OjE0OjAyOjcwOmNmOmNmOmM3OmVmOjUxOjJkOmM0OjY4OjhlOjU4OgogICAgICAgICAgICAgICAgICAgIGJjOmQzOjQ3Ojg0OjE0OmQ3OmUwOmVjOjNlOmFjOjY5OjdmOjczOmEwOjY4OgogICAgICAgICAgICAgICAgICAgIDJhOjVhOjhiOjE5OjIxOjM2OmZlOjYyOmY1OmQyOjM2Ojg0OjUyOjVkOmE5OgogICAgICAgICAgICAgICAgICAgIGJmOmMwOjk5OmQyOjI5OmUyOjU5OjdmOmNhOjczOjk5OjA3OjZjOjIzOmY1OgogICAgICAgICAgICAgICAgICAgIGI1OjU1OjA3OmEwOjNlOmEwOmE5OjI3OjFkOmM3OjMyOjM5Ojk2OjQzOmUyOgogICAgICAgICAgICAgICAgICAgIDkyOjVmOmRjOjZkOjJkOmJlOjE5OjVkOjdjOmQ1OjYzOmIxOmQ1OjAyOjYzOgogICAgICAgICAgICAgICAgICAgIGFhOjMxOmRiOjcxOjZjOjU5OmZhOjE2OjM4OjUzOjUxOjRmOjFlOjcxOmNhOgogICAgICAgICAgICAgICAgICAgIDA3OjM2OjNkOmFlOmM0OmY5OmI4OjBkOjI4OmRiOjMwOmE2OjZiOmFjOjBiOgogICAgICAgICAgICAgICAgICAgIDY0OjE2OjFlOjRkOjBjOmMzOjQ5OmMwOmJkOmY2OmUwOmExOmQ1OjAwOjg4OgogICAgICAgICAgICAgICAgICAgIGY0OjA0Ojc4OmY3OmUwOjE4OjA3OmQ5OjNlOmFhOjE5OmM2OmVmOjI5Ojg4OgogICAgICAgICAgICAgICAgICAgIGJiOmRhOmQwOjU5OmJjOjc3OmI3OjU3OjkyOjFjOmNjOjVjOjdiOjhiOmJiOgogICAgICAgICAgICAgICAgICAgIGJmOjI2OmEwOjY3OmU2OjM3OjU3OmY4OjFlOjMxOjJhOjkyOmU0OjIyOjcwOgogICAgICAgICAgICAgICAgICAgIDBkOjJjOmE0OmVjOjBhOjBhOmRiOjJmOjY2OmU4OmYwOjNlOjcwOjBjOmJmOgogICAgICAgICAgICAgICAgICAgIDI3OmExOmIxOmM1OjUzOjdmOmNmOmQwOmZjOjQ2OjM4OmI5OmQ3OmNkOmE3OgogICAgICAgICAgICAgICAgICAgIDRkOmM3OmJmOjkwOjlkOjFhOjk1OjBlOjdmOmJjOjc0OjdlOmEyOjhiOmUzOgogICAgICAgICAgICAgICAgICAgIGNlOmExCiAgICAgICAgICAgICAgICBFeHBvbmVudDogNjU1MzcgKDB4MTAwMDEpCiAgICAgICAgWDUwOXYzIGV4dGVuc2lvbnM6CiAgICAgICAgICAgIFg1MDl2MyBCYXNpYyBDb25zdHJhaW50czogCiAgICAgICAgICAgICAgICBDQTpGQUxTRQogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICBENTo5MzpEOTowMzo3Rjo1RDoyRTpBQjpBRTo0MTpERTpGQjpGMjo0RTpBODoyQjpFMTo5QTo5OTpBRQogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIGtleWlkOjVDOjUzOjdFOjE2OjkyOjU4OkZCOjY5OkIzOkYzOkRCOjg2OkM4OjY0OjE1OkUyOjc1OkU1OkMzOkU4CiAgICAgICAgICAgICAgICBEaXJOYW1lOi9DTj1Db3VjaGJhc2UgQ0EKICAgICAgICAgICAgICAgIHNlcmlhbDpGRjpERDpDRjpENTo3RDpGRTo1RDowRgoKICAgICAgICAgICAgWDUwOXYzIEV4dGVuZGVkIEtleSBVc2FnZTogCiAgICAgICAgICAgICAgICBUTFMgV2ViIFNlcnZlciBBdXRoZW50aWNhdGlvbgogICAgICAgICAgICBYNTA5djMgS2V5IFVzYWdlOiAKICAgICAgICAgICAgICAgIERpZ2l0YWwgU2lnbmF0dXJlLCBLZXkgRW5jaXBoZXJtZW50CiAgICAgICAgICAgIFg1MDl2MyBTdWJqZWN0IEFsdGVybmF0aXZlIE5hbWU6IAogICAgICAgICAgICAgICAgRE5TOiouY2ItZXhhbXBsZS5ja3Rlc3QyLnN2YywgRE5TOiouY2t0ZXN0Mi5zdmMKICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgIDQ0OmZlOjU4OjEzOmYwOjQzOjNkOjcxOjA1OjkzOjBjOjg0OjQ5OmY2Ojk1Ojk1OmRlOjVlOgogICAgICAgICA2NTo3YzphNjpmMjo1NDo2Mjo3YTo3ODpjYTphMTo0MTpiMjo3MTozZToxOTpjZTphNjpkNDoKICAgICAgICAgODc6MTQ6OTI6NDc6Y2Q6ODE6M2I6ODQ6ODQ6NzI6OWU6YmM6NDI6NTE6NDM6Yjk6Y2Q6NDc6CiAgICAgICAgIGEyOjk5OjljOjM2Ojg1OjRkOmI1OmIzOjljOjIwOmM5OmYxOjViOmJjOjcwOmI1OjRhOmMwOgogICAgICAgICBmZjo4NDpjMDowZjo0NTowNjo4NDo0Mzo0YzoyMjozYjpiYzplMzpkYToyYTo3ZDplOTo3NToKICAgICAgICAgM2Q6YWI6OTY6Mjc6NzE6M2E6M2Y6MmY6N2U6M2Y6YWY6MGM6Yzc6YWY6ODM6MDU6ODk6OWU6CiAgICAgICAgIGZiOmU1OjI4OjIyOjgxOjlhOjk2OjIyOjlkOmQxOjc1Ojc5OmQxOjhhOmVmOjlhOmMyOjZhOgogICAgICAgICA5MjphMjpjMzpjNjphYjo2YTpkMToyMTpmNzowNDphMDo4YTo5ZjoxMTphMTo4NzpjNTphNDoKICAgICAgICAgNGI6YjE6OGQ6Nzk6NTI6ZTk6ZTI6MDI6ZTM6NWU6YmE6NDQ6YmQ6MmE6NDk6MGI6NGQ6MmM6CiAgICAgICAgIDI0OjFmOmQ5OjY1OmI1OjA3OjUxOjBhOjk2OjQ1OjBiOjJiOjY1OjliOjM0OjA4OmYyOjgwOgogICAgICAgICA1ODoxMToxYjo2MTpiZToxMTphNTpkZTpkNjoxMDoyYjpkZjowNToyMjo2MDo4YjozNDpkOToKICAgICAgICAgNGE6OTY6OGQ6MjE6YmY6ZTA6YWY6Mjk6ZTc6NjU6YjM6NDk6YzQ6ZGE6Nzg6YmQ6MzA6Mjg6CiAgICAgICAgIDE4OjQ1Ojk5OjMwOjA5OjAzOjkxOjg3OjBmOmE4OmZiOmU4OjY4Ojk2OjZhOmU4OjRjOjViOgogICAgICAgICA0ZTo2MDo5NjpkMjo3ZjpkMToyNTowNjo0MjpjMDo5Mjo5MjozZTpkMDplMTozYTpkMTo3YjoKICAgICAgICAgNjc6ZDk6ZDE6MDkKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpVENDQW5HZ0F3SUJBZ0lRWkFpK255NDNQOEtNeUFRbGNXaTNKREFOQmdrcWhraUc5dzBCQVFzRkFEQVgKTVJVd0V3WURWUVFEREF4RGIzVmphR0poYzJVZ1EwRXdIaGNOTVRrd09URTVNVE0xT1RVNVdoY05Nakl3T1RBegpNVE0xT1RVNVdqQWJNUmt3RndZRFZRUUREQkJqYjNWamFHSmhjMlV0YzJWeWRtVnlNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2VmpNc2swVENjbXZSMU5ieTQ0clQyYzV0YTdoUyt5cDIvVVkKMldYbHRoUUNjTS9QeCs5UkxjUm9qbGk4MDBlRUZOZmc3RDZzYVg5em9HZ3FXb3NaSVRiK1l2WFNOb1JTWGFtLwp3Sm5TS2VKWmY4cHptUWRzSS9XMVZRZWdQcUNwSngzSE1qbVdRK0tTWDl4dExiNFpYWHpWWTdIVkFtT3FNZHR4CmJGbjZGamhUVVU4ZWNjb0hOajJ1eFBtNERTamJNS1pyckF0a0ZoNU5ETU5Kd0wzMjRLSFZBSWowQkhqMzRCZ0gKMlQ2cUdjYnZLWWk3MnRCWnZIZTNWNUljekZ4N2k3dS9KcUJuNWpkWCtCNHhLcExrSW5BTkxLVHNDZ3JiTDJibwo4RDV3REw4bm9iSEZVMy9QMFB4R09Mblh6YWROeDcrUW5ScVZEbis4ZEg2aWkrUE9vUUlEQVFBQm80SE1NSUhKCk1Ba0dBMVVkRXdRQ01BQXdIUVlEVlIwT0JCWUVGTldUMlFOL1hTNnJya0hlKy9KT3FDdmhtcG11TUVjR0ExVWQKSXdSQU1ENkFGRnhUZmhhU1dQdHBzL1BiaHNoa0ZlSjE1Y1Bvb1J1a0dUQVhNUlV3RXdZRFZRUUREQXhEYjNWagphR0poYzJVZ1EwR0NDUUQvM2MvVmZmNWREekFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQVRBTEJnTlZIUThFCkJBTUNCYUF3TWdZRFZSMFJCQ3N3S1lJWUtpNWpZaTFsZUdGdGNHeGxMbU5yZEdWemRESXVjM1pqZ2cwcUxtTnIKZEdWemRESXVjM1pqTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCRS9sZ1Q4RU05Y1FXVERJUko5cFdWM2w1bApmS2J5VkdKNmVNcWhRYkp4UGhuT3B0U0hGSkpIellFN2hJUnlucnhDVVVPNXpVZWltWncyaFUyMXM1d2d5ZkZiCnZIQzFTc0QvaE1BUFJRYUVRMHdpTzd6ajJpcDk2WFU5cTVZbmNUby9MMzQvcnd6SHI0TUZpWjc3NVNnaWdacVcKSXAzUmRYblJpdSthd21xU29zUEdxMnJSSWZjRW9JcWZFYUdIeGFSTHNZMTVVdW5pQXVOZXVrUzlLa2tMVFN3awpIOWxsdFFkUkNwWkZDeXRsbXpRSThvQllFUnRodmhHbDN0WVFLOThGSW1DTE5ObEtsbzBoditDdktlZGxzMG5FCjJuaTlNQ2dZUlprd0NRT1JodytvKytob2xtcm9URnRPWUpiU2Y5RWxCa0xBa3BJKzBPRTYwWHRuMmRFSgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: couchbase-operator-admission-cktest2
      namespace: cktest2
      path: /couchbaseclusters/validate
  name: couchbase-operator-admission-cktest2.cktest2.svc
  rules:
  - apiGroups:
    - couchbase.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - couchbaseclusters

